// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	GetOrder(ctx context.Context, id int64) (Order, error)
	UpdateOrderFinished(ctx context.Context, arg UpdateOrderFinishedParams) (Order, error)
	UpdateOrderObservations(ctx context.Context, arg UpdateOrderObservationsParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
